[theme]
primaryColor = "#00ffff"
backgroundColor = "#0a0c10"
secondaryBackgroundColor = "#1e2a3a"
textColor = "#ffffff"
font = "sans serif"

[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false
